---
title: "Navigating the Headlines: A Closer Look at UK’s Inflation and Housing Market"
date: 2022-05-24
description: "Yesterday’s headlines have brought a wave of optimism about the UK’s economy. We’re seeing reports suggesting that the ‘UK inflation set to fall ‘dramatically’ to 'a two-year low’ and about how little house prices have fallen."
# image: ""
# twitter-card:
#   image: ""
# open-graph:
#   image: ""
categories:
  - measurements
resources:
  - "img/*"
doi: ""
citation: true
bibliography: ../../../../files/references.bib
csl: ../../../../files/amj.csl
---

Yesterday’s headlines have brought a wave of optimism about the UK’s economy. We’re seeing reports suggesting that the ‘UK inflation set to fall ‘dramatically’ to two-year low’ and about how little house prices have fallen. These stories suggest a reassuring picture: inflation is easing, and the housing market is showing signs of resilience. It’s tempting to feel a sense of relief from these updates.

But, should we accept these headlines at face value? As we look under the hood, it becomes evident that the truth is more nuanced. Let’s unpack why we should not to be too optimistic based on headline figures alone.

## Inflation Figures:

- While the drop in inflation to 4.6% is significant, it’s crucial to understand the temporary factors contributing to this decrease, like the slowdown in energy prices.
- Headlines might not fully capture ongoing economic challenges or the fact that other areas might still be experiencing price hikes.
- In fact, when looking into the details of the inflation number, there are several areas where inflation has not reduced, or has even increased. For example, Food and beverage went from 12.1% to 10.1%, down yes, but still very high.
- The all services figure is 6.6 down from 6.9, but again very high (compared to a 2% target) and showing little signs of going down yet.
- Most of the fall in inflation is due to fall in energy prices, but last year, people in the UK received a £400 subsidy to help with energy bills, no such thing this year. So the actual price paid by household for energy is very similar this year to what it was last year with the subsidy.
- Finally, 4.6% is still more than twice the 2% target of the Bank of England.

While the recent fall in inflation is a positive sign, it’s important to keep in perspective that inflation rates remain high. There is no cause for celebration. Though salary growth has overtaken headline inflation, offering some hope, we must remember that wages have lagged behind inflation for a while, squeezing household budgets. And wage growth is still lower than inflation on some types of goods and services, for example, food. Additionally, as unemployment begins to tick upwards, wage growth will decelerate. This means it could take considerable time for wages to recover to their level from before this inflationary period in real terms (adjusted for inflation).

## Housing Market Data:

- The reported 0.1% annual fall in house prices masks the regional variations and doesn’t necessarily indicate a nationwide trend.
- The ONS House Price Index is based on completed transactions, meaning the data is lagged (the lag varies by the time it takes for transactions to be completed which makes correcting for it harder) and might not reflect the current market conditions.

For those currently in the process of buying or selling a house, relying solely on lagged indicators like the ONS House Price Index can be misleading. While these indicators show only a slight annual fall in house prices, more current data suggests that prices are falling further. This discrepancy underscores the importance of considering up-to-date market information in your decision-making process. In a changing market, basing decisions on outdated data could lead you to overpay for a house.

On both inflation, and house prices, my comments are only some of the reason to be critical of the headlines that you have seen, there are many other things that make interpreting headline figures harder, and mean that we often see misleading headlines. One example of other factor to look at would be seasonal variation.

There is a lot of good commentary out there (for example, on YouTube) if you want to go deeper into inflation or housing data.

If you are wanting to go deeper on measurement, David Hand excellent [very short introduction](https://uk.bookshop.org/a/7155/9780198779568) has a chapter on economic measurement that is well worth a read.

These examples highlight the importance of critically analyzing news. Headlines, while informative, are just the tip of the iceberg and they are written to make you click on them (just like the title of this article, sorry not sorry). The real story often lies beneath the surface, in the details and context that are not immediately apparent.

This brief exercise in data literacy shows us how vital it is to look beyond the headlines to avoid misconceptions. In a world overflowing with information, a little data literacy goes a long way in helping us understand the world around us. In the context of inflation slowing, looking under the hood makes it clear that people are going to continue struggling financially for a while. And looking at house prices, it might save you a lot of money to deconstruct the figure because you will avoid overpaying for a house in a falling market.

Note: Some of the links are affiliate links, which means that, at no extra cost to you, I might get a small commission if you click them and make a qualifying purchase.