---
title: "Airport Fascination"
date: 2025-10-10
description: "It is not what it looks like. I am fascinated by airports "
image: ""
twitter-card:
  image: ""
open-graph:
  image: ""
categories:
  - book
  - writing
  - science communication
resources:
  - "img/*"
doi: ""
citation: true
draft: true
---


Because https://bsky.app/profile/econmaett.github.io said Hate the Game gave "airport vibes", I went down a rabbit hole of reflecting on my fascination with "airport books".
You've been warned, if you read on, you're not allowed to complain I have wasted your time.

<!-- insert screenshot -->

I aspire to write airport business books.
Or at least write one.
How did I get there and does it makes sense to write an airport business book for me?
Probably not right now, but in the future, I hope so.

One reason I hope to be able to write such a book in the future is that I am some sort of fascination for them. 
I find them extremely enticing and therefore, I buy a fair number of them.

# Definition: What is an Airport Book?


# Why do I find them so hard to resist?

I am a sucker for books that promise to reveal a big secret and inevitably fall short because the secret is either obvious or something I already know.
What will probably keep me from ever writing one of these book is that I don't know how to pick the right level of argument... These book almost always come out as patronising or helplessly simplistic 

I think this might come from a deep seated fear that there is something that everyone knows that I don't.

Sure, I know little, but everyone else also has a narrow range of knowledge.
But you do not get rid of impostor syndrom easily.


# Reasons to write one

# Bad reasons

Money

Fame

At least do something once in my life that someone in my family understands

# Good reasons

They actually get read

There is maybe some of the things I have figured out that could be useful to others but does not easily fit into a course I could teach.

It looks like a different challenge than writing an academic book, so if I manage to finish this book, this might be a good new challenge.


